services:
  localstack:
    image: localstack/localstack
    env_file:
      - .env
    environment:
      - SERVICES=sqs,dynamodb
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    command: --sql_mode=""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  app:
    build: .
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./uv.lock
    volumes:
      - ./stream_cdc:/app/stream_cdc
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./README.md:/app/README.md
      # - .:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        uv venv .venv &&
        uv sync &&
        watchmedo auto-restart --recursive --directory=stream_cdc --patterns='**/*.py' --no-restart-on-command-exit -- python -m stream_cdc.profiling.profiling_app
      "
volumes:
  mysql_data:
