apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stream-cdc
  name: stream-cdc
  labels:
    app: stream-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-cdc
      version: stream-cdc
  template:
    metadata:
      labels:
        app: stream-cdc
        version: stream-cdc
    spec:
      containers:
      - name: stream-cdc
        image: sykescottages/stream-cdc:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: stream-cdc-secret
        - configMapRef:
            name: stream-cdc-config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
