
name: Ruff Checks
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Cache uv virtual environment
      uses: actions/cache@v3
      id: venv-cache
      with:
        path: |
          .venv
          ~/.cache/uv
        key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml', '**/requirements.txt', '**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-${{ matrix.python-version }}-
    - name: Install package in development mode
      run: |
        source .venv/bin/activate
        uv pip install -e .
    - name: Check code formatting with Ruff
      run: |
        source .venv/bin/activate
        ruff check .
        ruff format --check .

